Repository Ensembl/ensembl-vep, pull requests merged in 2021-09, with the labels that each got.

#1047 Set tmp_dir to CODON right place.
  modules/Bio/EnsEMBL/VEP/Pipeline/DumpVEP/DumpVEP_conf.pm
Labels: bug

#1018 Variant Recoder - remove duplicated MANE transcripts
  modules/Bio/EnsEMBL/VEP/VariantRecoder.pm
  t/VariantRecoder.t
  t/test-genome-DBs/homo_vepiens/core/transcript_attrib.txt
Labels: release/105

#849 Ask metadata db whether there should be variation data and refuse to dump if missing
  modules/Bio/EnsEMBL/VEP/Pipeline/DumpVEP/DumpVEP_conf.pm
  modules/Bio/EnsEMBL/VEP/Pipeline/DumpVEP/InitDump.pm
Labels: release/103
