Repository Ensembl/ensembl-vep, pull requests merged in 2023-06, with the labels that each got.

#1423 Clinical significance - compare ref alleles
  modules/Bio/EnsEMBL/VEP/AnnotationSource/Database/Variation.pm
  modules/Bio/EnsEMBL/VEP/OutputFactory.pm
Labels: e111

#1394 Update dump VEP directories
  modules/Bio/EnsEMBL/VEP/Pipeline/DumpVEP/BaseVEP.pm
  modules/Bio/EnsEMBL/VEP/Pipeline/DumpVEP/DistributeDumps.pm
  modules/Bio/EnsEMBL/VEP/Pipeline/DumpVEP/JoinVEP.pm
  modules/Bio/EnsEMBL/VEP/Pipeline/DumpVEP/QCDump.pm
Labels: e111

#1368 Build Docker image for ARM and x86
  .github/workflows/docker.yml
  docker/Dockerfile
Labels: docker/singularity

#1407 Integrate StructuralVariantOverlap plugin features
  modules/Bio/EnsEMBL/VEP/AnnotationSource/File.pm
  modules/Bio/EnsEMBL/VEP/AnnotationSource/File/VCF.pm
  modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm
  modules/Bio/EnsEMBL/VEP/OutputFactory.pm
  modules/Bio/EnsEMBL/VEP/Parser.pm
  t/AnnotationSourceAdaptor.t
  t/AnnotationSource_File.t
  t/OutputFactory.t
Labels: release/110

#1399 Add support for breakend variants from VCF
  modules/Bio/EnsEMBL/VEP/AnnotationSource.pm
  modules/Bio/EnsEMBL/VEP/BaseVEP.pm
  modules/Bio/EnsEMBL/VEP/InputBuffer.pm
  modules/Bio/EnsEMBL/VEP/OutputFactory.pm
  modules/Bio/EnsEMBL/VEP/Parser.pm
  modules/Bio/EnsEMBL/VEP/Parser/VCF.pm
  t/AnnotationSource.t
  t/InputBuffer.t
  t/Parser_VCF.t
Labels: release/110

#1444 Fixing uploaded allele
  modules/Bio/EnsEMBL/VEP/Config.pm
  modules/Bio/EnsEMBL/VEP/Constants.pm
  modules/Bio/EnsEMBL/VEP/OutputFactory.pm
  modules/Bio/EnsEMBL/VEP/OutputFactory/VCF.pm
  modules/Bio/EnsEMBL/VEP/Parser.pm
  modules/Bio/EnsEMBL/VEP/Parser/VEP_input.pm
  t/AnnotationSource_Cache_Variation.t
  t/AnnotationSource_Cache_VariationTabix.t
  t/OutputFactory.t
  t/OutputFactory_JSON.t
  t/OutputFactory_Tab.t
  t/OutputFactory_VCF.t
  t/OutputFactory_VEP_output.t
  t/Runner.t
  t/VariantRecoder.t
Labels: release/110

#1398 Running nextflow-vep from another pipeline
  nextflow/nextflow.config
  nextflow/nf_modules/check_VCF.nf
  nextflow/nf_modules/generate_splits.nf
  nextflow/nf_modules/merge_VCF.nf
  nextflow/nf_modules/process_input.nf
  nextflow/nf_modules/read_VCF.nf
  nextflow/nf_modules/run_vep.nf
  nextflow/nf_modules/split_VCF.nf
  nextflow/workflows/run_vep.nf
Labels: release/110, nextflow
